package skill

var data = []string{
	"Skill",
	"COMPUTER LITERATE",
	"DRIVER",
	"AUTO MECHANIC",
	"CARPENTRY WORK",
	"MASONRY",
	"ELECTRICIAN",
	"STENOGRAPHY",
	"PAINTING JOBS",
	"EMBROIDERY",
	"SEWING DRESSES",
	"TAILORING",
	"BEAUTICIAN",
	"DOMESTIC CHORES",
	"GARDENING",
	"PHOTOGRAPHY",
	"PAINTER/ARTIST",
}
