package eligibility

var data = []string{
	"CAREER SERVICE PROFESSIONAL",
	"CAREER SERVICE EXECUTIVE ELIGIBILITY",
	"CAREER EXECUTIVE OFFICER ELIGIBILITY",
	"R.A. 1080",
	"CAREER SERVICE SUB - PROFESSIONAL",
	"CAREER EXECUTIVE SERVICE OFFICER",
	"POLICE OFFICER 1",
	"STENOGRAPHER",
	"SOIL TECHNOLOGIST",
	"DATA ENCODER",
	"FORESTRY EXTENSION SERVICE",
	"FIRE OFFICER 2",
}
